ADD: ksh0123 사전과제 제출
drum-grammer/docker-pro-wanted pull request #117
Opened 2023-03-30 13:35 UTC by ksh0123

2023-03-31 23:43 UTC, drum-grammer approved these changes
너무 잘 정리해주셨네요! 👍
사전 미션 확인 완료했습니다. ✅

그럼 4월 4일 수업때 뵐께요! ☺️

2023-03-31 23:43 UTC, drum-grammer commented on mission/ksh0123/ksh0123-mission.md
> +애플리케이션을 다양한 컴퓨팅 환경에서 이식성 있게 배포하는 기술입니다.
네 대테로 잘 정리해주셨네요! 👍

참조할 만한 보충 설명을 남깁니다:

컨테이너 기술은 애플리케이션을 실행하는 데 필요한 모든 것을 포함한 격리된 환경을 만드는 기술입니다.
이러한 격리된 환경을 컨테이너라고 하며,
애플리케이션을 컨테이너 안에 패키징하여 다른 시스템에서도 쉽게 실행할 수 있도록 해줍니다.

이러한 특성 때문에 컨테이너는 빠르고 가벼운 실행 환경을 제공하며,
개발과 배포를 간편하게 해줍니다. 
그래서 `배포하는 기술` 이라기 보다는, `배포를 간편하게 하는 기술` 이라고 서술하는게 조금 더 맞을 것 같네요.

2023-04-01 00:22 UTC, drum-grammer requested changes
사전 미션 확인 완료했습니다. ✅
코멘트 한번 확인 부탁드려요. 🙏

2023-04-03 02:18 UTC, ksh0123 commented
확인했습니다! 감사합니다 :)

2023-04-12 11:19 UTC, closed without merging