headgen/사전 과제 제출
drum-grammer/docker-pro-wanted pull request #144
Opened 2023-03-31 16:27 UTC by headgen

원티드 프리온보딩 백엔드 챌린지 사전 과제 제출입니다.

2023-04-01 00:24 UTC, drum-grammer requested changes
사전 미션 확인 완료했습니다. ✅
코멘트 확인 부탁드려요~
그럼 4월 4일 수업때 뵐께요! ☺️

2023-04-01 00:24 UTC, drum-grammer commented on mission/headgen/mission-headgen.md
> +    - 리눅스에 유래되었으며, 애플리케이션을 환경에 구애받지 않고 실행하는 기술.
네.  맞습니다.

컨테이너 기술은 가상화 기술의 일종으로, 애플리케이션을 격리된 환경에서 실행하고 관리하는 기술입니다.

- 가상화 기술의 일종
- 애플리케이션을 격리된 환경에서 실행하고 관리하는 기술

만약 추후에 누군가에게 설명하신다면, 위  두가지 포인트로 서술하시면 좋을 것 같아요. 👍

2023-04-01 01:24 UTC, headgen commented on mission/headgen/mission-headgen.md
> +    - 리눅스에 유래되었으며, 애플리케이션을 환경에 구애받지 않고 실행하는 기술.
피드백 감사합니다!! 좋은 주말 보내세요~

2023-04-12 11:22 UTC, drum-grammer approved these changes

2023-04-12 11:22 UTC, merged