bangjaeyoung - 사전과제 제출
drum-grammer/docker-pro-wanted pull request #42
Opened 2023-03-27 06:45 UTC by bangjaeyoung

bangjaeyoung - 사전과제 제출합니다.

2023-03-29 04:17 UTC, drum-grammer requested changes

2023-03-29 04:17 UTC, drum-grammer commented on mission/bangjaeyoung/mission.md
> +개발자가 컨테이너에 소프트웨어를 제공할 수 있는 PaaS 도구로, 가상 컨테이너를 제공하여 원하는 형태로 환경을 세팅할 수 있도록 도와주는 플랫폼
해당 내용은 조금 수정이 필요할 것 같아요.

도커는 PaaS 도구가 아니라 
PaaS 도구에서 도커를 활용하는 거라고 보시면 좋을 것 같습니다.

도커와 PaaS에 대해 조금 더 리서치 해보시고, 수정해보시면 
도커를 이해하시는 데 도움이 될 것 같습니다. 🙌

2023-03-29 04:17 UTC, drum-grammer commented on mission/bangjaeyoung/mission.md
> +- 도커 이미지 : 도커 프레임워크에서 작동하도록 생성된 컨테이너
도커 이미지는 컨테이너는 아닙니다. 
컨테이너를 만들기 위해 이미지를 사용하는 거라고 봐주시면 될 것 같습니다.

2023-03-29 04:17 UTC, drum-grammer commented on mission/bangjaeyoung/mission.md
> +- 도커 이미지 : 도커 프레임워크에서 작동하도록 생성된 컨테이너
도커 이미지는 
도커 컨테이너를 생성하는데 필요한 모든 정보와 설정값들이 저장된 파일입니다. 

도커 이미지는 
애플리케이션의 실행에 필요한 모든 파일 시스템, 라이브러리, 실행 파일, 설정 파일 등을 포함하고 있습니다. 

이 이미지를 이용하여 도커 엔진은 컨테이너를 만들고 실행합니다.

2023-03-29 06:32 UTC, bangjaeyoung commented on mission/bangjaeyoung/mission.md
> +- 도커 이미지 : 도커 프레임워크에서 작동하도록 생성된 컨테이너
@drum-grammer 감사합니다. 수정 필요한 부분 리서치 후 수정하였습니다 :)

2023-03-30 14:45 UTC, drum-grammer approved these changes
너무 잘 정리해주셨네요! 👍
사전 미션 확인 완료했습니다. ✅

그럼 4월 수업때 뵐께요! ☺️

2023-03-31 15:41 UTC, merged